### ISSUE TITLE
Malformed requests cause server to hang

### ISSUE THREAD

**Issue by stefanbaur-neugelb** [jaydenseric/apollo-upload-server#102]
If there is malformed JSON content in `map` I do get the following stack trace:
```
SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at Busboy.parser.on (./node_modules/apollo-upload-server/lib/middleware.js:80:50)
    at Busboy.emit (events.js:182:13)
    at Busboy.emit (./node_modules/busboy/lib/main.js:38:33)
    at PartStream.onEnd (./node_modules/busboy/lib/types/multipart.js:261:15)
    at PartStream.emit (events.js:187:15)
    at Dicer.onPart (./node_modules/busboy/lib/types/multipart.js:120:13)
    at Dicer.emit (events.js:182:13)
    at Dicer.emit (./node_modules/dicer/lib/Dicer.js:80:35)
    at Dicer._oninfo (./node_modules/dicer/lib/Dicer.js:181:12)
    at SBMH.<anonymous> (./node_modules/dicer/lib/Dicer.js:127:10)
    at SBMH.emit (events.js:182:13)
    at SBMH._sbmh_feed (./node_modules/streamsearch/lib/sbmh.js:159:14)
    at SBMH.push (./node_modules/streamsearch/lib/sbmh.js:56:14)
    at Dicer._write (./node_modules/dicer/lib/Dicer.js:109:17)
```

or if there is malformed JSON content in `operations` I get 
```
SyntaxError: Unexpected token a in JSON at position 0
    at JSON.parse (<anonymous>)
    at Busboy.parser.on (./node_modules/apollo-upload-server/lib/middleware.js:66:29)
    at Busboy.emit (events.js:182:13)
    at Busboy.emit (./node_modules/busboy/lib/main.js:38:33)
    at PartStream.onEnd (./node_modules/busboy/lib/types/multipart.js:261:15)
    at PartStream.emit (events.js:187:15)
    at Dicer.onPart (./node_modules/busboy/lib/types/multipart.js:120:13)
    at Dicer.emit (events.js:182:13)
    at Dicer.emit (./node_modules/dicer/lib/Dicer.js:80:35)
    at Dicer._oninfo (./node_modules/dicer/lib/Dicer.js:181:12)
    at SBMH.<anonymous> (./node_modules/dicer/lib/Dicer.js:127:10)
    at SBMH.emit (events.js:182:13)
    at SBMH._sbmh_feed (./node_modules/streamsearch/lib/sbmh.js:159:14)
    at SBMH.push (./node_modules/streamsearch/lib/sbmh.js:56:14)
    at Dicer._write (./node_modules/dicer/lib/Dicer.js:109:17)
    at doWrite (_stream_writable.js:410:12)
```

both error at the respective `JSON.parse(value)` and ***totally crashing the server***.

Probably somewhat related to #96 .

Is there any workaround to at least keep the server running? Otherwise this needs urgent fix

**Comment by jaydenseric** [comment]
This has been fixed, but not released yet: https://github.com/jaydenseric/apollo-upload-server/blame/master/src/middleware.mjs#L90

The coming major update is my priority, I am working on it as we speak 🚢
