### ISSUE TITLE
MultipartParser.end(): stream ended unexpectedly: state = START

### ISSUE THREAD

**Issue by FBerthelot** [jaydenseric/apollo-upload-server#21]
Hello,

I have a **restify** server and I use the `apolloUploadExpress`.

But it doesn'st work. I have two error:

The first one: 
```bash
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at form.parse (/Users/berthel/developpement/pro/missions/gptw/web-reporting-api/node_modules/apollo-upload-server/dist/apollo-upload-server.js:29:25)
    at IncomingForm.<anonymous> (/Users/berthel/developpement/pro/missions/gptw/web-reporting-api/node_modules/formidable/lib/incoming_form.js:102:9)
    at emitOne (events.js:116:13)
    at IncomingForm.emit (events.js:211:7)
    at IncomingForm._error (/Users/berthel/developpement/pro/missions/gptw/web-reporting-api/node_modules/formidable/lib/incoming_form.js:290:8)
    at IncomingMessage.<anonymous> (/Users/berthel/developpement/pro/missions/gptw/web-reporting-api/node_modules/formidable/lib/incoming_form.js:132:14)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
```

The second one:
```bash
Error: MultipartParser.end(): stream ended unexpectedly: state = START
        at form.parse (/Users/berthel/developpement/pro/missions/gptw/web-reporting-api/node_modules/apollo-upload-server/dist/apollo-upload-server.js:25:25)
        at IncomingForm.<anonymous> (/Users/berthel/developpement/pro/missions/gptw/web-reporting-api/node_modules/formidable/lib/incoming_form.js:102:9)
        at emitOne (events.js:116:13)
        at IncomingForm.emit (events.js:211:7)
        at IncomingForm._error (/Users/berthel/developpement/pro/missions/gptw/web-reporting-api/node_modules/formidable/lib/incoming_form.js:290:8)
        at IncomingMessage.<anonymous> (/Users/berthel/developpement/pro/missions/gptw/web-reporting-api/node_modules/formidable/lib/incoming_form.js:132:14)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1056:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

I think the issue came from `formidable` but Have you any idea ?

Many thanks :)

**Comment by jaydenseric** [comment]
Does restify parse multipart forms for you, before it gets to the upload middleware?

The `Unexpected token u` likely comes from `undefined`.

You're not on Google Cloud Functions are you? See https://github.com/jaydenseric/apollo-upload-server/issues/19.

**Comment by FBerthelot** [comment]
Many thanks ! It was that.

I use restify body parser plugin.

For those who have the same issue, my body parser look like this now:

```javascript
  server.use(restify.plugins.bodyReader());
  server.use((req, res, next) => {
    if (req.contentType().toLowerCase() === 'multipart/form-data') {
      next();
    }
    restify.plugins.bodyParser()[1](req, res, next);
  });
```
