### ISSUE TITLE
[AWS Lambda] SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by RishitKedia** [jaydenseric/apollo-upload-server#58]
Hey there! 👋

First off, thanks for all the work you're doing for us, @jaydenseric! 🙏

So, I'm trying to use `apollo-upload-server` on **AWS Lambda** using [`Serverless`](https://github.com/serverless/serverless) and [`aws-serverless-express`](https://github.com/awslabs/aws-serverless-express).

It works fine when there's no file being uploaded, but when a file is uploaded, I get the following error:

```
SyntaxError: Unexpected end of JSON input
at Object.parse (native)
at Busboy.parser.on (/var/task/node_modules/apollo-upload-server/lib/middleware.js:66:29)
at emitMany (events.js:127:13)
at Busboy.emit (events.js:201:7)
at Busboy.emit (/var/task/node_modules/busboy/lib/main.js:38:33)
at PartStream.onEnd (/var/task/node_modules/busboy/lib/types/multipart.js:261:15)
at emitNone (events.js:91:20)
at PartStream.emit (events.js:185:7)
at Dicer.onPart (/var/task/node_modules/busboy/lib/types/multipart.js:120:13)
at emitOne (events.js:96:13)
at Dicer.emit (events.js:188:7)
at Dicer.emit (/var/task/node_modules/dicer/lib/Dicer.js:80:35)
at Dicer._oninfo (/var/task/node_modules/dicer/lib/Dicer.js:181:12)
at SBMH.<anonymous> (/var/task/node_modules/dicer/lib/Dicer.js:127:10)
at emitMany (events.js:127:13)
at SBMH.emit (events.js:201:7)
```

The request payload from `apollo-upload-client` looks like this:

```
------WebKitFormBoundarymnT1gqXGJmeSwDDv
Content-Disposition: form-data; name="operations"

{"operationName":"ShareMutation","variables":{"state":"SHARE","text":"Hey!","image":null,"childPosts":[{"accountId":"cjekhdqfl2m7d0104fh88d8r8","state":"SHARE","contentSameAsParentPost":true}]},"query":"mutation ShareMutation($state: POST_STATE!, $text: String, $image: Upload, $childPosts: [ChildPostInput!]) {\n  share(state: $state, text: $text, image: $image, childPosts: $childPosts) {\n    id\n    state\n    text\n    image {\n      id\n      size\n      contentType\n      url\n      __typename\n    }\n    errors {\n      id\n      code\n      name\n      message\n      __typename\n    }\n    childPosts {\n      id\n      account {\n        id\n        __typename\n      }\n      state\n      contentSameAsParentPost\n      text\n      image {\n        id\n        size\n        contentType\n        url\n        __typename\n      }\n      errors {\n        id\n        code\n        name\n        message\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"}
------WebKitFormBoundarymnT1gqXGJmeSwDDv
Content-Disposition: form-data; name="map"

{"0":["variables.image"]}
------WebKitFormBoundarymnT1gqXGJmeSwDDv
Content-Disposition: form-data; name="0"; filename="blob"
Content-Type: image/png


------WebKitFormBoundarymnT1gqXGJmeSwDDv--
```

I'm also setting `multipart/form-data` as a **Binary Media Type** in both **AWS API Gateway** and `aws-serverless-express`.

I'm using the latest versions of `apollo-upload-server` and `apollo-upload-client`.

Thanks for your time! 😃

**Comment by jaydenseric** [comment]
Thanks for the thanks 😊

It looks like AWS API Gateway does not work well with multipart requests: https://stackoverflow.com/questions/41557109/aws-api-gateway-form-data-support

Perhaps the multipart stream is cut off in the middle of JSON.

I am not really familiar with AWS so I'm not sure what your best option is, but troubleshooting is something beyond the scope of this package as it must send multipart requests.

Feel free to discuss this in the `#uploads` channel of the Apollo Slack.
