### ISSUE TITLE
File Upload Not working

### ISSUE THREAD

**Issue by gauravmakkar** [jaydenseric/apollo-upload-server#72]
schema.graphql
```
scalar Upload
type Mutation {
    uploadMasterData(file:Upload):File
}
```
resolver.js
```
const rootResolvers = {
    Upload: GraphQLUpload,
    Mutation: {
        uploadMasterData(root, variables, context) {
            return processUpload(variables.file)
        },

    }
}
```

server.js
```
app.use(apolloUploadExpress());
app.use('/graphql', graphqlExpress((req) => { /**returns context**/})
```

HOC
```
const UPLOAD_MASTER_DATA_MUTATION=gql`
    mutation($file: Upload!) {
        uploadMasterData(file: $file) {
            id
            filename
            encoding
            mimetype
            path
        }
    }
`

const withMasterDataUpload=graphql(UPLOAD_MASTER_DATA_MUTATION, {
    props: ({mutate, ownProps}) => ({
        uploadMasterData: function ({file}) {
            mutate({variables: {file:file}})
        },
    }),
});



export default compose(withMasterDataUpload)(ComponentTab)
```

From the componentTab calling it by this.props.uploadMasterData({file:fileObject})

I don't understand what I'm doing wrong.

**Comment by gauravmakkar** [comment]
Response:

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Must provide document<br> &nbsp; &nbsp;at invariant (/Users/gaurav.m/Projects/GreyOrange/gor.butler.ui.bff/node_modules/graphql/jsutils/invariant.js:18:11)<br> &nbsp; &nbsp;at Object.validate (/Users/gaurav.m/Projects/GreyOrange/gor.butler.ui.bff/node_modules/graphql/validation/validate.js:58:34)<br> &nbsp; &nbsp;at doRunQuery (/Users/gaurav.m/Projects/GreyOrange/gor.butler.ui.bff/node_modules/apollo-server-core/src/runQuery.ts:143:30)<br> &nbsp; &nbsp;at /Users/gaurav.m/Projects/GreyOrange/gor.butler.ui.bff/node_modules/apollo-server-core/src/runQuery.ts:69:39<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:178:7)</pre>
</body>
</html>

**Comment by jaydenseric** [comment]
Sorry for the late response, did you work it out?

If not, what is the request body being sent from the client to the server? Is it a multipart form? You can find out using the Chrome dev tools network activity tab.

**Comment by jaydenseric** [comment]
Closing due to inactivity; feel free to continue the conversation if it's still an issue.

**Comment by sebastian-schlecht** [comment]
I'm also seeing this.

**Comment by jaydenseric** [comment]
@sebastian-schlecht we need a little more to go on. Are you using the latest versions of the client and server? Did it ever work for you? What is the request body being sent from the client?

**Comment by sebastian-schlecht** [comment]
Hey Jayden,

sorry for the poor explanation, I was on the run writing this.

Essentially, the latest version of apollo-upload-client in combination with apollo-upload-server did never work for us. We use apollo-upload-server (2.0.4) in combination with some custom code derived from apollo-upload-client (I believe it's based off version 6).

I tried to upgrade everything yesterday (using latest & greatest apollo-upload-server and apollo-upload-client from npm). This is when I encountered the error above. 

As a side note: I had quite some trouble using extract-text > 3.0, it just didn't work for me at any point for react-native. That's another reason why we had to stick with older versions of your packages.

Thanks though for providing this!

**Comment by jaydenseric** [comment]
@sebastian-schlecht 

> We use apollo-upload-server (2.0.4) in combination with some custom code derived from apollo-upload-client (I believe it's based off version 6)

They are really old versions. The latest versions use v2 of the [GraphQL multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec), so if you are migrating some custom implementations you will need to conform accordingly and also update all your resolvers to handle the newer promises/streams API. What did you need to customize specifically?

> I had quite some trouble using extract-text > 3.0, it just didn't work for me at any point 

Do you mean `extract-files`? How exactly did it not work, and how did you get by without it?

**Comment by sebastian-schlecht** [comment]
> They are really old versions. The latest versions use v2 of the GraphQL multipart request spec, so if you are migrating some custom implementations you will need to conform accordingly and also update all your resolvers to handle the newer promises/streams API. What did you need to customize specifically?

Good to know. I didn't have much time yesterday so I just used the new packages as a drop in replacement. If I remember correctly, we changed the error handler in apollo-upload-client only (this change should be deprecated by now, I've seen you also updated the handlers to match apollo-link-http schemes). We did not change anything for apollo-upload-server.


> Do you mean extract-files? How exactly did it not work, and how did you get by without it?
Yes, sorry for the typo. Version 3 or greater did not extract any files on our end. Therefore, requests were not migrated to be multipart and naturally files where sent.

I will have a look at the spec and potentially retry to upgrade.
